apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "general.fullname" . }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 100%
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "general.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") $ | sha256sum | trunc 10 }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") $ | sha256sum | trunc 10 }}
      labels:
        {{- include "general.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      serviceAccountName: {{ include "general.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ if not .Values.command }} [] {{ end }}
          {{- if .Values.command -}}
          {{ toYaml .Values.command | nindent 8 }}
          {{- end }}
          args: {{ if not .Values.args }} [] {{ end }}
          {{- if .Values.args -}}
          {{ toYaml .Values.args | nindent 8 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.probes -}}
          {{- toYaml .Values.probes | nindent 10 }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "general.fullname" $ }}
          - secretRef:
              name: {{ include "general.fullname" $ }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}





