
{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "general.fullname" . }}
type: Opaque
data:
  {{- toYaml .Values.secrets | nindent 2 }}
{{- end }}

---

{{- if .Values.workers -}}
{{- range $i, $val := .Values.workers }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $val.name }}-secret
type: Opaque
data:
  {{- toYaml $val.secrets | nindent 2 }}

---
{{- end -}}
{{- end -}}
